[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "Hugo Zzo Theme"
  languageName = "Espa√±ol"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/es"
